In [7]:
pip install pandas psycopg2 sqlalchemy

Requirement already satisfied: pandas in c:\users\kbpat\miniconda3\lib\site-packages (2.2.3)
Requirement already satisfied: psycopg2 in c:\users\kbpat\miniconda3\lib\site-packages (2.9.10)
Requirement already satisfied: sqlalchemy in c:\users\kbpat\miniconda3\lib\site-packages (2.0.41)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kbpat\miniconda3\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kbpat\miniconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kbpat\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kbpat\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\kbpat\miniconda3\lib\site-packages (from sqlalchemy) (3.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kbpat\miniconda3\lib\site-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: six>=1.5 in c:\users\kbpat\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Import Libraries

In [8]:
import pandas as pd
import numpy as np

Load the CSV Data

In [9]:
# Load hospital data
df = pd.read_csv('../data/Hospital_General_Information.csv')

# Show the shape and first few rows
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
df.head()

Rows: 5384, Columns: 38

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,1,8,2,NaN,8,8,NaN,12,10,NaN
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,8,1,NaN,8,8,NaN,12,12,NaN
2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,0,7,2,NaN,8,8,NaN,12,11,NaN
3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,7,0,NaN,8,8,NaN,12,7,NaN
4,010008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,2,0,NaN,8,Not Available,5.0,12,6,NaN

Explore Columns

In [10]:
df.columns.tolist()

['Facility ID',
 'Facility Name',
 'Address',
 'City/Town',
 'State',
 'ZIP Code',
 'County/Parish',
 'Telephone Number',
 'Hospital Type',
 'Hospital Ownership',
 'Emergency Services',
 'Meets criteria for birthing friendly designation',
 'Hospital overall rating',
 'Hospital overall rating footnote',
 'MORT Group Measure Count',
 'Count of Facility MORT Measures',
 'Count of MORT Measures Better',
 'Count of MORT Measures No Different',
 'Count of MORT Measures Worse',
 'MORT Group Footnote',
 'Safety Group Measure Count',
 'Count of Facility Safety Measures',
 'Count of Safety Measures Better',
 'Count of Safety Measures No Different',
 'Count of Safety Measures Worse',
 'Safety Group Footnote',
 'READM Group Measure Count',
 'Count of Facility READM Measures',
 'Count of READM Measures Better',
 'Count of READM Measures No Different',
 'Count of READM Measures Worse',
 'READM Group Footnote',
 'Pt Exp Group Measure Count',
 'Count of Facility Pt Exp Measures',
 'Pt Exp Group Footnote',
 'TE Group Measure Count',
 'Count of Facility TE Measures',
 'TE Group Footnote']

Clean Column Names

In [11]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('/', '_')
df.head()

,facility_id,facility_name,address,city_town,state,zip_code,county_parish,telephone_number,hospital_type,hospital_ownership,...,count_of_readm_measures_better,count_of_readm_measures_no_different,count_of_readm_measures_worse,readm_group_footnote,pt_exp_group_measure_count,count_of_facility_pt_exp_measures,pt_exp_group_footnote,te_group_measure_count,count_of_facility_te_measures,te_group_footnote
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,1,8,2,NaN,8,8,NaN,12,10,NaN
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,8,1,NaN,8,8,NaN,12,12,NaN
2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,0,7,2,NaN,8,8,NaN,12,11,NaN
3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,7,0,NaN,8,8,NaN,12,7,NaN
4,010008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,2,0,NaN,8,Not Available,5.0,12,6,NaN

Check for Missing Values

In [12]:
df.isna().sum()

facility_id                                            0
facility_name                                          0
address                                                0
city_town                                              0
state                                                  0
zip_code                                               0
county_parish                                          0
telephone_number                                       0
hospital_type                                          0
hospital_ownership                                     0
emergency_services                                     0
meets_criteria_for_birthing_friendly_designation    3154
hospital_overall_rating                                0
hospital_overall_rating_footnote                    2766
mort_group_measure_count                               0
count_of_facility_mort_measures                        0
count_of_mort_measures_better                          0
count_of_mort_measures_no_different                    0
count_of_mort_measures_worse                           0
mort_group_footnote                                 3509
safety_group_measure_count                             0
count_of_facility_safety_measures                      0
count_of_safety_measures_better                        0
count_of_safety_measures_no_different                  0
count_of_safety_measures_worse                         0
safety_group_footnote                               3390
readm_group_measure_count                              0
count_of_facility_readm_measures                       0
count_of_readm_measures_better                         0
count_of_readm_measures_no_different                   0
count_of_readm_measures_worse                          0
readm_group_footnote                                4296
pt_exp_group_measure_count                             0
count_of_facility_pt_exp_measures                      0
pt_exp_group_footnote                               3194
te_group_measure_count                                 0
count_of_facility_te_measures                          0
te_group_footnote                                   4490
dtype: int64

Cleaning Data

In [13]:
# Keep leading zeroes in zipcodes
df['zip_code'] = df['zip_code'].astype(str).str.zfill(5)

# Telephone number is string
df['telephone_number'] = df['telephone_number'].astype(str)

# Convert numeric ratings to numeric types
df['hospital_overall_rating'] = pd.to_numeric(df['hospital_overall_rating'], errors='coerce')

Create output folder

In [15]:
import os

os.makedirs('../output', exist_ok=True)

Save Cleaned Data

In [ ]:
# Save to cleaned CSV

df.to_csv('../output/cleaned_hospital_data.csv', index=False)

print("âœ… Cleaned CSV saved at ../output/cleaned_hospital_data.csv")

âœ… Cleaned CSV saved at ../output/cleaned_hospital_data.csv

: